compressionLevel: 0

enableGlobalCache: true

nmMode: hardlinks-global

nodeLinker: node-modules

npmRegistryServer: "https://artifactory-ehv.ta.philips.com/artifactory/api/npm/dl-common-npm"

yarnPath: .yarn/releases/yarn-4.0.2.cjs
